### ISSUE TITLE
Cannot load database configuration: (NoMethodError) undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by samuelnunoo** [aspc/aspc-website#204]
# Description
When running ```docker-compose docker-compose run web bundle exec rails db:create```
I get the error ```Cannot load database configuration: (NoMethodError) undefined method `[]' for nil:NilClass```

# Stack Trace 
```/usr/local/bin/ruby: warning: shebang line ending with \r may cause problems

(erb):89:in `<main>': Cannot load database configuration: (NoMethodError)

undefined method `[]' for nil:NilClass

from /usr/local/lib/ruby/2.6.0/erb.rb:901:in `eval'

from /usr/local/lib/ruby/2.6.0/erb.rb:901:in `result'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application/configuration.rb:172:in `database_configuration'

from /usr/local/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `each'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `on_load'

from /usr/local/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'

from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'

from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'

from /aspc/config/environment.rb:5:in `<main>'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'

from config.ru:3:in `block in <main>'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:27:in `app'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:51:in `start'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:142:in `tap'

=> Booting Puma

=> Rails 5.2.4.4 application starting in development 

=> Run `rails server -h` for more startup options

Exiting

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:142:in `perform'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

from bin/rails:4:in `<main>'

(erb):89:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

from /usr/local/lib/ruby/2.6.0/erb.rb:901:in `eval'

from /usr/local/lib/ruby/2.6.0/erb.rb:901:in `result'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application/configuration.rb:172:in `database_configuration'

from /usr/local/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `each'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/lazy_load_hooks.rb:42:in `on_load'

from /usr/local/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'

from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'

from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'

from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'

from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'

from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'

from /aspc/config/environment.rb:5:in `<main>'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'

from config.ru:3:in `block in <main>'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:27:in `app'

from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:51:in `start'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:142:in `tap'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands/server/server_command.rb:142:in `perform'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'

from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'

from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'

from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'

from bin/rails:4:in `<main>'```

**Comment by samuelnunoo** [comment]
This error occurs when the master.key is not configured properly or does not exist in the config folder. Adding it resolves the issue. This was discovered after visiting ```https://stackoverflow.com/questions/41905756/cannot-load-rails-application-database-configuration-nomethoderror-with-lau```
